platform :ios, '6.0'
pod 'Parse', '~> 1.2.15'
pod 'TestFlightSDK', '~> 1.3.0.beta2'
pod 'AFNetworking', '~> 2.0.0'
pod 'MBProgressHUD', '~> 0.5'
pod 'MLPAutoCompleteTextField', '~> 1.5'
pod 'BFCropInterface', '~> 1.0.0'
pod 'RDGPUImage', '~> 0.1.1'
